#!/usr/bin/env python3
"""Extract the balance inputs the economy simulator needs, from the real configs.

The simulator has to run headless, outside Roblox, so it can be part of `check.sh`
instead of something a human remembers to do. But `EquipmentConfig` and `ZoneConfig`
both require siblings or `game:GetService`, which the plain `luau` CLI cannot resolve.

Rather than let the simulator carry its own copy of the numbers — which would drift
from the game within a week and quietly make every projection a lie — this script
parses the configs and writes `scripts/_balance_inputs.luau`. That generated module is
checked in, regenerated by `check.sh`, and diffed in CI, so a balance change that is not
reflected in the simulation shows up as a dirty file rather than as nothing at all.

`Formulas` is NOT extracted: it is pure Luau with no requires, so the simulator requires
it directly and always uses the same math the game does. `RankConfig` would qualify too
except that its rows carry a `Color3`, which does not exist outside Roblox — so its
thresholds are extracted and its lookup is three lines the simulator does itself.

Usage:
    python3 scripts/extract_balance.py            # write the module
    python3 scripts/extract_balance.py --check    # fail if it would change
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ROOT / "src" / "ReplicatedStorage" / "Modules"
OUTPUT = ROOT / "scripts" / "_balance_inputs.luau"

# Fields we need from each equipment definition, and their Luau types.
EQUIPMENT_FIELDS = {
    "Id": str,
    "StatId": str,
    "BaseGain": float,
    "RepInterval": float,
    "UnlockPower": float,
}

ZONE_FIELDS = {
    "Id": str,
    "RequiredPower": float,
    "GainMultiplier": float,
}

RANK_FIELDS = {
    "Id": str,
    "MinPower": float,
}


def _entries(source: str, table_name: str) -> list[str]:
    """Split a `local <table_name>: {...} = { {...}, {...} }` into its entry bodies.

    Brace-counting rather than a regex over the whole table: entries contain nested
    tables and strings with braces in them, and a greedy regex silently merges two
    entries into one, which would drop a station from the simulation without failing.
    """
    match = re.search(rf"local {table_name}[^=]*= \{{", source)
    if match is None:
        raise SystemExit(f"[extract_balance] Could not find `local {table_name}` table")

    start = match.end()
    depth = 1
    index = start
    entries: list[str] = []
    entry_start: int | None = None

    while index < len(source):
        char = source[index]
        if char == "{":
            if depth == 1:
                entry_start = index + 1
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 1 and entry_start is not None:
                entries.append(source[entry_start:index])
                entry_start = None
            elif depth == 0:
                return entries
        index += 1

    raise SystemExit(f"[extract_balance] Unbalanced braces in `{table_name}`")


def _field(entry: str, name: str, kind: type):
    if kind is str:
        match = re.search(rf'\b{name}\s*=\s*"([^"]*)"', entry)
        return match.group(1) if match else None
    match = re.search(rf"\b{name}\s*=\s*(-?[\d.eE+]+)\s*,", entry)
    return float(match.group(1)) if match else None


def _collect(path: Path, table_name: str, fields: dict[str, type]) -> list[dict]:
    source = path.read_text()
    rows = []
    for entry in _entries(source, table_name):
        row = {name: _field(entry, name, kind) for name, kind in fields.items()}
        if row["Id"] is None:
            continue
        missing = [name for name, value in row.items() if value is None]
        if missing:
            raise SystemExit(f"[extract_balance] {row['Id']} is missing {', '.join(missing)}")
        rows.append(row)
    return rows


def _equipment_rows(path: Path) -> list[dict]:
    """Parse the compact equipment(...) calls used to enforce +1 base stat/second."""
    source = path.read_text()
    pattern = re.compile(
        r'equipment\("(?P<id>[^"]+)",\s*"[^"]+",\s*"(?P<family>[^"]+)",\s*'
        r'(?P<interval>\d+(?:\.\d+)?),\s*"[^"]+",\s*"[^"]+"\)'
    )
    rows = []
    for match in pattern.finditer(source):
        interval = float(match.group("interval"))
        rows.append({
            "Id": match.group("id"),
            "StatId": match.group("family"),
            "BaseGain": interval,
            "RepInterval": interval,
            "UnlockPower": 0.0,
        })
    if len(rows) != 35:
        raise SystemExit(f"[extract_balance] Expected 35 equipment() rows, found {len(rows)}")
    return rows


def _constant(path: Path, name: str) -> float:
    source = path.read_text()
    match = re.search(rf"^local {name} = (-?[\d.eE+]+)$", source, re.MULTILINE)
    if match is None:
        raise SystemExit(f"[extract_balance] Could not find `local {name}` in {path.name}")
    return float(match.group(1))


def _number(value: float) -> str:
    return str(int(value)) if value == int(value) else repr(value)


def render() -> str:
    equipment = _equipment_rows(MODULES / "EquipmentConfig.luau")
    zones = _collect(MODULES / "ZoneConfig.luau", "zones", ZONE_FIELDS)
    ranks = _collect(MODULES / "RankConfig.luau", "ranks", RANK_FIELDS)

    training = ROOT / "src" / "ServerScriptService" / "Core" / "TrainingService.luau"
    combo_step = _constant(training, "COMBO_STEP")
    max_combo = _constant(training, "MAX_COMBO_MULTIPLIER")

    lines = [
        "--!strict",
        "--[[",
        "\tGENERATED by scripts/extract_balance.py — do not edit.",
        "",
        "\tThe balance inputs scripts/simulate.luau needs, lifted verbatim from",
        "\tEquipmentConfig, ZoneConfig, RankConfig and TrainingService. It exists because",
        "\tthe plain luau CLI cannot resolve those modules' requires, and a simulator",
        "\tcarrying its",
        "\town copy of the numbers would drift from the game and quietly make every",
        "\tprojection a lie.",
        "",
        "\tRegenerate with `python3 scripts/extract_balance.py`. check.sh verifies this",
        "\tfile is current, so a balance change that skipped the simulator fails there.",
        "]]",
        "",
        "local BalanceInputs = {}",
        "",
        f"BalanceInputs.COMBO_STEP = {_number(combo_step)}",
        f"BalanceInputs.MAX_COMBO_MULTIPLIER = {_number(max_combo)}",
        "",
        "BalanceInputs.Equipment = {",
    ]

    for row in equipment:
        lines.append(
            "\t{{ Id = \"{Id}\", StatId = \"{StatId}\", BaseGain = {gain}, "
            "RepInterval = {interval}, UnlockPower = {unlock} }},".format(
                Id=row["Id"],
                StatId=row["StatId"],
                gain=_number(row["BaseGain"]),
                interval=_number(row["RepInterval"]),
                unlock=_number(row["UnlockPower"]),
            )
        )

    lines += ["}", "", "BalanceInputs.Zones = {"]
    for row in zones:
        lines.append(
            "\t{{ Id = \"{Id}\", RequiredPower = {power}, GainMultiplier = {mult} }},".format(
                Id=row["Id"],
                power=_number(row["RequiredPower"]),
                mult=_number(row["GainMultiplier"]),
            )
        )

    lines += ["}", "", "BalanceInputs.Ranks = {"]
    for row in ranks:
        lines.append(
            '\t{{ Id = "{Id}", MinPower = {power} }},'.format(
                Id=row["Id"], power=_number(row["MinPower"])
            )
        )

    lines += ["}", "", "return BalanceInputs", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else None

    if args.check:
        if current != rendered:
            print(
                "[extract_balance] scripts/_balance_inputs.luau is stale. "
                "Run: python3 scripts/extract_balance.py",
                file=sys.stderr,
            )
            return 1
        print("Balance inputs are current.")
        return 0

    OUTPUT.write_text(rendered)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
